### ISSUE TITLE
Time is 30 min off (behind) in version 1.0.2

### ISSUE THREAD

**Issue by rrubanov** [Phambili-Tech/Newt_Display#16]
Time is 30 min off (behind) in version 1.0.2

**Comment by darianbjohnson** [comment]
Can you tell me what time zone you are in, and the time zone that Newt thinks it's it (that information will be available in the "Settings" menu). My Newt is running 1.0.2. and it's displaying the correct time.

**Comment by rrubanov** [comment]
Im @ PST, Newt's timezone -- America/Los_Angeles

Reseted via 'Reset Wifi'. And now it's just showing random time. Current time: ```19:52```. Newt is showing: ```8:06```

I can see in network logs request for ```pool.ntp.org``` when Newt boot up.

**Comment by darianbjohnson** [comment]
That's really weird. Try to turn on/off Newt again. No need to reset wifi, just restart the device with the reset button on the back (or us the on/off switch)- I just want it to go through the boot sequence one more time.

I don't know what the problem is... I've been thinking of going away from the ntp call, and instead sending the correct time via MQTT. Maybe that'll fix this problem... thought that doesn't solve the problem that you're currently having. 

Are you able to manually reinstall the code via Arduino? If so, download/roll-back to Newt_Display version 1.0.1 [in the Arduino Library Manager] and manually upload the Newt example. Be sure to use the Arduino ESP32 board library version 2.0.3 [2.0.4 has a big that impacts wifi reset].

I'm happy to get on the phone this weekend if you want to troubleshoot it live.

**Comment by rrubanov** [comment]
Took battery off. Restarted Newt. Time is back to nominal. Thank you.

**Comment by andypiper** [comment]
I had the same issue after the upgrade, but a restart fixed it. Super odd.

**Comment by darianbjohnson** [comment]
I haven't seen this issue for a while, so I'm going to close, and will reopen if we see the issue again.
