### ISSUE TITLE
Feels like Weather and other weather details

### ISSUE THREAD

**Issue by darianbjohnson** [Phambili-Tech/Newt_Display#6]
Provide additional weather details (such as "feel like" temp wind speed, humidity, etc)

**Comment by darianbjohnson** [comment]
Tossed some ideas in the [discussions area](https://github.com/Phambili-Tech/Newt_Display/discussions/11). Welcome any feedback.

**Comment by tjfoth** [comment]
I had mentioned in an email that it would be great to have a screen composition language that would allow mapping from MQTT received variables to a location on the screen.  I’ll see if I can find something.  There’s a lot of cool stuff in the OpenWeather payload that some people might like to include.  Sunrise, sunset, average min and max temperatures for the day.  Since you’re getting the forecast data you may want to include some details for the next hour.

**Comment by darianbjohnson** [comment]
Enhancement in 1.1.0-RC-1 available for testing

**Comment by darianbjohnson** [comment]
Tested in beta and released
